### ISSUE TITLE
WxCpService.oauth2getUserInfo方法不会去刷新access token

### ISSUE THREAD

**Issue by zhoujinliang** [chanjarster/weixin-java-tools#104]
如题，如果access token过期，这个方法就没法使用了。

**Comment by chanjarster** [comment]
@zhoujinliang 本issue和 #64 重复，请查阅

**Comment by chanjarster** [comment]
@zhoujinliang 你是对的， WxCpService.oauth2getUserInfo的确有错误

**Comment by zhoujinliang** [comment]
抓紧时间改，我现在在每一次调用之前都去调用一下getAccessToken

**Comment by chanjarster** [comment]
@zhoujinliang 嘿哥们儿，你不是我的老板，你没有资格命令我。

而且在develop分支里已经修复了，你瞎啊。

**Comment by sugar-xj** [comment]
人家只是说了“抓紧时间改”  你用不着这种态度回复吧，我上次提issue你的态度也很冷漠

**Comment by zhoujinliang** [comment]
@chanjarster 太敏感了，我们做软件的，尤其是自己的软件，要是有这么大的bug，都不用别人提醒我。你坐这个lib是为了方便大家，我们都会很感谢你。希望你在能力范围之内，对待自己的产品态度要认真，别无其他。

**Comment by krisjin** [comment]
“抓紧时间改” 这句偶觉的也不应该说，开源的都是大家业余做的，哪有那么多时间，有bug改了可以提request。

**Comment by chanjarster** [comment]
@zhoujinliang @krisjin @sugar-xj 这个bug现在develop分支里解决了没有？如果解决了给个反馈。

顺便说点其他的

开源软件需要大家共同协助，发现bug如果软件开发人员没时间改或者响应不及时可以fork修改，然后pull request。

这个bug大小的问题先不讨论，就根据我个人水平来说，有bug是很正常的，至于要求我对这个项目认真负责，理论上也不成立，源代码都公布出来了，如果你想改进直接拿来改就行了，如果有点贡献精神，也可以提个pull request，当然近期我也没有要把这个项目烂尾的打算。

你选我的项目肯定是因为这个项目看上去还挺靠谱的，api和文档也比较齐全，而且我也不认为自己的态度不认真，也没必要受别人提醒。

关于我态度冷漠的问题，我只能说我不热情，冷漠倒不至于，毕竟我每个issue都有回复（当然有些回复可能是错误的），如果很介意这个，那么请自己fork然后维护。

总之一粗糙话就是，没求你用，爱用不用，听上去挺伤感情，但就是这么回事儿。

**Comment by gejo** [comment]
Daniel同学还是很靠谱的，每次我问问题都能很及时的回答，而且这个项目省了我们很多的开发时间，在这里要十分感谢Daniel的辛勤付出//bow！

**Comment by chanjarster** [comment]
别的就不说了，我也不想引起太多争论，现在比较关心这个bug算不算修复了，需要你们的反馈。

**Comment by zhoujinliang** [comment]
说句实话，我也想办你完善这个库，看到bug恨不得马上修改，不过最近项目实在太紧，年后有空我可以加入

**Comment by chanjarster** [comment]
@zhoujinliang 感谢。其实如果遇到bug，继承一下我的类，稍微改一下就行了，这个项目代码很简单一看就明白，等有空了再pull request也算是给大家做了贡献。

**Comment by zhoujinliang** [comment]
嗯，原来用的csdn上一个人写的demo，代码差点恶心死我了，我后来想自己写，看到你的我就直接用了，年后我pull下你的代码，我在用的过程中出现问题直接改，然后上传吧
