### ISSUE TITLE
WxCpService.oauth2buildAuthorizationUrl方法设计错误

### ISSUE THREAD

**Issue by lqviwz** [chanjarster/weixin-java-tools#105]
如支持设置redirect_uri，将更方便接口开发

**Comment by chanjarster** [comment]
@lqviwz 微信的相关文档里有redirect_uri参数吗？能否给个链接瞅瞅。

**Comment by lqviwz** [comment]
http://qydev.weixin.qq.com/wiki/index.php?title=企业获取code
还有获取userinfo里agentid
现在您在代码里是取的storageconfig里的固定值，目前倒是能通过先改config 再调用接口的方法间接实现

**Comment by chanjarster** [comment]
agentid这个问题我是这么想的，企业号里的每个应用对应一个storage，redirect_uri可以加上

**Comment by chanjarster** [comment]
redirect_uri的问题，我看公众号的文档里是这么写的
   
   > 在微信公众号请求用户网页授权之前，开发者需要先到公众平台官网中的开发者中心页配置授权回调域名

在企业号里，也需要对应用设置“可信域名”。

   > 可作为应用OAuth2.0网页授权回调页面的域名，以确保安全可靠
    域名要求：配置的域名规范为全域名匹配，如配置了www.qq.com，则该域名下页面都可进行OAuth2.0授权，
    但weixin.qq.com则无法进行OAuth2.0授权。

所以感觉上redirect_uri不是调用的时候能随便填写的，而是实现配置好的一个东西。

所以当初就放在了storage里。

@lqviwz

**Comment by blademainer** [comment]
我觉得原有的api是可以的，目前我正在开发的思路就是：
先自己构造一个接口，该接口可以传入一个uri，然后将该uri存入session或cookie内，再跳转到微信的OAuth认证
```java
   @RequestMapping("/oauth2/redirect")
    public String weiXinOAuthRedirect(String url, HttpSession session) {
        session.setAttribute(WEI_XIN_OAUTH_REDIRECT_URI_SESSION_NAME, url);
        String s = config.getWxMpService().oauth2buildAuthorizationUrl(WxConsts.OAUTH2_SCOPE_USER_INFO, null);
        return "redirect:" + s;// 跳转认证地址
    }
```
在微信认证完的跳转的接口内，我们可以将上面存进session内的uri再读取出来进行跳转就行了
微信oauth2redirectUri=http://host.com/oauth2.html
```java
    @RequestMapping("/oauth2")
    public String oauthPage(String code, HttpServletRequest request, HttpServletResponse response, HttpSession session) throws WxErrorException {
        // 即将跳转的地址
        String url = (String) session.getAttribute(WEI_XIN_OAUTH_REDIRECT_URI_SESSION_NAME);

        WxMpOAuth2AccessToken wxMpOAuth2AccessToken = config.getWxMpService().oauth2getAccessToken(code);
        WxMpUser wxMpUser = config.getWxMpService().oauth2getUserInfo(wxMpOAuth2AccessToken, null);
        session.setAttribute(WEI_XIN_USER_ID_SESSION_NAME, wxMpUser.getOpenId());

            // 使用户登录
            PUser userByWeiXinBind = userService.getUserByWeiXinBind(wxMpUser.getOpenId());
            if(userByWeiXinBind != null){
                session.setAttribute("user", userByWeiXinBind);
            }


        wxMpOAuth2AccessToken = config.getWxMpService().oauth2refreshAccessToken(wxMpOAuth2AccessToken.getRefreshToken());

        return "redirect:" + url;
    }
```

**Comment by chanjarster** [comment]
@blademainer 我觉得把url放到state参数里更好，因为你这样一来的话就要求weiXinOAuthRedirect方法和oauthPage必须是在同一个容器里，如果你以后做负载均衡的话就没用了。

**Comment by sugar-xj** [comment]
我也建议redirect_uri参数化， 你上面说的可信域名 是指域名，不是特定的一个url，这个需求我上次也跟你提过，建议你加一下

**Comment by zhoujinliang** [comment]
agentid 的处理我也觉得不妥，写死在storage

**Comment by chanjarster** [comment]
@sugar-xj 可信域名这我再验证一下，可能我当时是理解错误了。

@zhoujinliang 和agentid有关的方法可能在你的应用场景下都会有一点不便，这个我综合考虑一下。
