### ISSUE TITLE
微信公众号的开发模式下自动回复request请求，可以连续respons若干个消息吗

### ISSUE THREAD

**Issue by erwinx** [chanjarster/weixin-java-tools#106]
条件
1.开发模式下
2.例如用户发送test关键字，连续反馈给用户2个图片消息，1个单图文，1个多图文

官方文档是只是推送回复的时候post一个xml
连续post若干个不同类型的xml可行吗？还是回复post了一个xml之后，整个req和resp就结束了？
注：非开发模式下，微信官方平台是可以设置连续回复多个不同消息的

**Comment by chanjarster** [comment]
这个是java servlet api决定的，一次请求（不论是get还是post），只能有一次响应。

连续回复多个不同消息属于主动发送消息，详情见wiki
