### ISSUE TITLE
建议支持多企业号

### ISSUE THREAD

**Issue by zhang017** [chanjarster/weixin-java-tools#108]
目前的接口，支持单个企业号的多个应用。
建议扩展为支持多企业号

**Comment by chanjarster** [comment]
若要支持一个企业号多个应用是有比较严苛的先决条件的：必须每个应用的token和AESEncodingKey都一样才可以。

按照公众号的设计思路，企业号里的各个应用之间应该是互相独立的（token和AESEncodingKey都不一样），进而也就是说企业号之间也是互相独立的。

所以支持单个企业号多个应用和多个企业号多个应用的方式是一致的。这个方法就是针对每个应用构造一套WxCpConfigStorage和WxCpServiceImpl。然后每个应用都有一个独立的url。

**Comment by zhang017** [comment]
思路和第二种方法一样
1.私有化WxCpConfigStorage
    1). WxCpService接口均增加WxCpConfigStorage
    2). 从ThreadLocal中取WxCpConfigStorage
2.调用WxCpService之前，初始化WxCpConfigStorage

项目运行在集群环境中，将所有WxCpConfigStorage放入集群Cache，使用时从Cache中读取
