### ISSUE TITLE
关于WxSession的sessionid

### ISSUE THREAD

**Issue by zhang017** [chanjarster/weixin-java-tools#110]
读了wiki中关于WxSession的文章，个人认为sessionid使用：企业号+应用号+FromUserName 比较合适。

**Comment by gejo** [comment]
非常赞同

**Comment by chanjarster** [comment]
有道理，晚上改改

**Comment by chanjarster** [comment]
不对啊，每个应用的都应该有一套单独的router、configstorage、service，如此一来sessionId就不需要加上企业号+应用号来区分了。

**Comment by gejo** [comment]
一般一个企业号会有多个应用，所以session一般agentId+userId就够了
如果一套router, configstorage, service支持多个企业号，那么session还要加上corpId

**Comment by zhang017** [comment]
视情况而定
我们项目中有多个企业号和多个应用，所以使用corpId+agentId+userId
