### ISSUE TITLE
针对tag发送消息时报错

### ISSUE THREAD

**Issue by am-wangjin** [chanjarster/weixin-java-tools#112]
出错原因是
me.chanjar.weixin.cp.util.json.WxCpMessageGsonAdapter
第37行
 messageJson.addProperty("totag", message.getToUser());
应该为
 messageJson.addProperty("totag", message.getToTag());

**Comment by chanjarster** [comment]
You are right

> ÔÚ 2015Äê3ÔÂ23ÈÕ£¬16:21£¬am-wangjin <notifications@github.com> Ð´µÀ£º
> 
> WxCpMessageGsonAdapter
