### ISSUE TITLE
企业号oauth2getUserInfo报errcode=40029, errmsg=invalid code

### ISSUE THREAD

**Issue by am-wangjin** [chanjarster/weixin-java-tools#113]
问题出在WxCpServiceImpl的
448行
    return oauth2getUserInfo(code, wxCpConfigStorage.getAgentId());
调用
  String[] oauth2getUserInfo(String agentId, String code)方法时候参数顺序传递错误

**Comment by chanjarster** [comment]
这种错误还真是丢人啊。。。

**Comment by am-wangjin** [comment]
:)

**Comment by am-wangjin** [comment]
不过还是感谢你的工作成果，我能省很多事。

**Comment by chanjarster** [comment]
也感谢你，像你这样精确定位bug的issue很久没见过了。

**Comment by am-wangjin** [comment]
:)
