### ISSUE TITLE
wiki中群发消息-图文消息-demo代码有错误

### ISSUE THREAD

**Issue by ililing** [chanjarster/weixin-java-tools#114]
// 先上传图文消息里需要的图片
WxMediaUploadResult uploadResult = wxMpService.mediaUpload(WxConsts.MEDIA_IMAGE, WxConsts.FILE_JPG, inputStream);

变量名应该为：uploadResult -》uploadMediaRes

**Comment by chanjarster** [comment]
thanks，fixed
