### ISSUE TITLE
 微信错误 errcode=48001, errmsg=api unauthorized

### ISSUE THREAD

**Issue by erwinx** [chanjarster/weixin-java-tools#117]
您好，我有一个问题想请教一下，如下：
1.服务器已经通过认证
2.“网页授权获取用户基本信息”设置正确，并且使用一级域名“www.xx.com”
3.引导授权代码如下：
wxMpService.oauth2buildAuthorizationUrl(WxConsts.OAUTH2_SCOPE_BASE, null)
4.换取用户代码如下：
WxMpService wxMpService = (WxMpService)servletContext.getAttribute("wxMpService");	
WxMpOAuth2AccessToken oAuth2AccessToken = wxMpService.oauth2getAccessToken(code);
WxMpUser wxMpUser = wxMpService.oauth2getUserInfo(oAuth2AccessToken, "zh_CN");
openid = wxMpUser.getOpenId();
通过以上代码，返回错误信息“ 微信错误 errcode=48001, errmsg=api unauthorized”，想请教一下原因，谢谢。

**Comment by chanjarster** [comment]
scope不对，用snsapi_userinfo

http://mp.weixin.qq.com/wiki/17/c0f37d5704f0b64713d5d2c37b468d75.html#.E7.AC.AC.E4.BA.8C.E6.AD.A5.EF.BC.9A.E9.80.9A.E8.BF.87code.E6.8D.A2.E5.8F.96.E7.BD.91.E9.A1.B5.E6.8E.88.E6.9D.83access_token

**Comment by erwinx** [comment]
我想使用WxConsts.OAUTH2_SCOPE_BASE方式，该调用什么方法？

**Comment by erwinx** [comment]
谢谢，以上问题已经解决。

**Comment by erwinx** [comment]
1.WxMpOAuth2AccessToken oAuth2AccessToken = wxMpService.oauth2getAccessToken(code);
多用户使用用时，总是提示如下信息：
　　微信错误 errcode=40029, errmsg=invalid code
2.还是调用以后，还需要调用刷新代码：
wxMpOAuth2AccessToken = wxMpService.oauth2refreshAccessToken(wxMpOAuth2AccessToken.getRefreshToken());

**Comment by chanjarster** [comment]
OAuth2AccessToken需要你自己维护，这个项目是不维护的。

**Comment by jackwangshukai** [comment]
想请问下你最后是怎么解决的。
