### ISSUE TITLE
问个问题，你这里的token和sign不需要持久化么？

### ISSUE THREAD

**Issue by alwjava365** [chanjarster/weixin-java-tools#118]
如果需要，应该如何做

**Comment by chanjarster** [comment]
不知道你要问什么

**Comment by alwjava365** [comment]
我看你这里说，accesstoken会自动判断是否失效，自动去刷新accesstoken是么？js_sign也这样么

**Comment by chanjarster** [comment]
自动刷新的access token是和微信通信需要的access token，其他的关于oauth的access token，前端js里的access token是不自动刷新的
