### ISSUE TITLE
路由拦截添加interceptor拦截出错

### ISSUE THREAD

**Issue by akrio714** [chanjarster/weixin-java-tools#121]
我使用的是1.1.3的mp版本。
当我对拦截规则添加interceptor，他后面的所有拦截都会失效。当满足interceptor拦截要求的时候可以正常进入interceptor对应的handler方法中，当interceptor对象复写的方法返回false时，则后面所有的拦截不会执行。比如在下面例子中兜底拦截就无效了。

wxMpMessageRouter
			//interceptor测试拦截
			.rule()
			.interceptor(new CommentInterceptor())
			.handler(new  ReceiveErroHandle())
			.end()
			//兜底拦截
			.rule()
		.async(false)
		.handler(new ReceiveErroHandle())
		.end();

CommentInterceptor类代码如下：
public class CommentInterceptor implements WxMpMessageInterceptor {

	@Override
	public boolean intercept(WxMpXmlMessage wxMessage,
			Map<String, Object> context, WxMpService wxMpService,
			WxSessionManager sessionManager) throws WxErrorException {
		return false;
	}

}
ReceiveErroHandle类代码如下：
public class ReceiveErroHandle implements WxMpMessageHandler{

	@Override
	public WxMpXmlOutMessage handle(WxMpXmlMessage wxMessage,
			Map<String, Object> context, WxMpService wxMpService,
			WxSessionManager sessionManager) throws WxErrorException {
		
			WxMpXmlOutTextMessage m = WxMpXmlOutMessage
					.TEXT()
					.content("您输入的信息非法，您输入的是："+wxMessage.getMsgType())
					.fromUser(wxMessage.getToUserName())
					.toUser(wxMessage.getFromUserName())
					.build();
			return m;
	}

}

**Comment by akrio714** [comment]
或者能提过给我一个完整一些的interceptor的用法的例子也可以。QQQ

**Comment by chanjarster** [comment]
你第一个rule没有设置任何匹配条件，那这个rule就已经是兜底规则了。

**Comment by akrio714** [comment]
我尝试在第一个rule添加一些规则，也是不行。

rule()
			.async(false)
			.msgType(WxConsts.XML_MSG_TEXT)
			.content("aaa")
			.interceptor(new CommentInterceptor())
			.handler(new  ReceiveCommentHandle())
			.end()
我只要添加interceptor。wxMpMessageRouter.route方法返回的就是空，只要把interceptor去掉就没事。你可以在右面的版本中添加一个interceptor的示例吗？我看到新版代码中interceptor的示例被取消了

**Comment by chanjarster** [comment]
消息规则匹配的逻辑是这样的：

1. 先看你的消息有没有匹配到某个rule
2. 如果匹配到了，执行这个rule的interceptor
3. 如果Interceptor返回false，规则不继续执行，自然就返回null
4. 如果interceptor返回true，继续执行handler
5. 如果rule是异步的，返回null
6. 如果rule是同步的，返回handler的返回值

你的这个Interceptor返回的是false，自然就返回null了

**Comment by akrio714** [comment]
首先感谢您的回答。
那如果我希望当Interceptor返回fasle 时，则执行下面的rule。
如果当Interceptor返回true时,则rule不继续执行,返回handler的返回值.
这个可以办到吗。
因为我想做一个问反馈功能，当用户点击问题反馈菜单(微信)时，我在WxSession做一个标志，用以说明该用户现在正在输入意见。所以我这里用到interceptor来判断WxSession中是否存在标志位。存在则进入意见的拦截，不存在继续其他拦截。因为用户的意见也许和某个文本拦截匹配，所以要先进行反馈的拦截，其他拦截都是反馈之后。
您帮我看下，像这种情况我应该怎样写。

**Comment by chanjarster** [comment]
写一个Wx*MessageMatcher，在里面放一个sessionManager，然后你就能在这里里面去判断是否在session里存在标志位了。

**Comment by akrio714** [comment]
您是指 WxMpMessageMatcher的实现类吗。我看到Override方法 public boolean match(WxMpXmlMessage message) 这里拿不到sessionManager.
还是说可以通过静态方法拿到sessionManager?

**Comment by chanjarster** [comment]
你new一个WxMpMessageMatcher，里面放个sessionManager就行了。
