### ISSUE TITLE
【噩耗】关于项目更新维护的说明

### ISSUE THREAD

**Issue by chanjarster** [chanjarster/weixin-java-tools#127]
本人最近太忙，本项目的更新、维护会极不靠谱，所以有些新特性和bug的修复会响应非常缓慢。

关于bug的问题，希望有同学能够自行找到原因并修复，然后向本项目提交pull request。

关于需求问题，因为这个项目本质上就是发起http请求给微信服务器，所以如果需要调用本项目没支持的api可以参考wiki的两篇文章：
* [公众号 如何调用未支持的接口](https://github.com/chanjarster/weixin-java-tools/wiki/MP_如何调用未支持的接口)
* [企业号 如何调用未支持的接口](https://github.com/chanjarster/weixin-java-tools/wiki/CP_如何调用未支持的接口)

总而言之，希望有同学能够有一点开源、贡献的精神向本项目提交pull request。

PS. 有事情别直接发我邮箱，请在这里提issue。

**Comment by haogrgr** [comment]
噩耗啊-.-

**Comment by xForMe** [comment]
绝对噩耗

**Comment by learnt** [comment]
理解

**Comment by zhoujinliang** [comment]
我发了邮件，因为你把issue给关了，哈哈

**Comment by cnlinjie** [comment]
好的。哈哈～

**Comment by smalljason** [comment]
各位，新手正在学习中，在错mp的demo时，使用xstream-1.4.7.jar，但是xpp3应该用哪个版本jar，一直报错，基本能下的都试过了，还是方向性错误，但是斑竹的demo程序没有改动，请各位高手解答一下。先谢了
