### ISSUE TITLE
这套工具支持多公众号么

### ISSUE THREAD

**Issue by alwjava365** [chanjarster/weixin-java-tools#137]
这套工具支持多公众号么

**Comment by ukid** [comment]
支持，参考wiki
https://github.com/chanjarster/weixin-java-tools/wiki/CP_如何支持多个企业号应用或企业号

**Comment by huangzf20** [comment]
貌似不支持啊。

**Comment by wdxxs2z** [comment]
配置文件可持久进数据库，至于token，其实很灵活，处理接口跟上token post就ok咯。

**Comment by ZhengZean** [comment]
多个号，无非就是处理对应多个configStorage然后多个wxservice
