### ISSUE TITLE
你好，API写的非常棒。

### ISSUE THREAD

**Issue by cnlinjie** [chanjarster/weixin-java-tools#146]
提个小建议。handle处理的时候返回content就可，fromUser和toUser可以自动填写，不知道这样有什么影响没有。用自定义拦截器可以实现吗？好像不能处理返回的WxMpXmlOutMessage数据。

**Comment by TimYi** [comment]
我跟着赞一个~

**Comment by TimYi** [comment]
跟着赞一个，链式api简直像Jquery一样富有美感。

**Comment by chanjarster** [comment]
WxMpXmlOutMessage的子类有很多，有些没有content属性，所以不能这么干。

1. WxMpXmlOutVoiceMessage
1. WxMpXmlOutImageMessage
1. WxMpXmlOutVideoMessage
1. WxMpXmlOutMusicMessage
1. WxMpXmlOutTextMessage
1. WxMpXmlOutNewsMessage
