### ISSUE TITLE
下一个版本中有支持永久素材库吗。

### ISSUE THREAD

**Issue by cnlinjie** [chanjarster/weixin-java-tools#149]
下一个版本中有支持永久素材库吗。

**Comment by chanjarster** [comment]
@codepiano 近期提交了关于这个的PR https://github.com/chanjarster/weixin-java-tools/pull/174

你可以在SNAPSHOT版试试

**Comment by cnlinjie** [comment]
@chanjarster 
恩的，之后回去测试下！感谢支持。
