### ISSUE TITLE
/java/me/chanjar/weixin/mp/api/WxMpServiceImpl.java 文件支付签名错误返回的问题

### ISSUE THREAD

**Issue by zhoujinliang** [chanjarster/weixin-java-tools#150]
WxMpServiceImpl.java文件的getJSSDKPayInfo方法中有以下语句：
String prepayId = wxMpPrepayIdResult.getPrepay_id();
    if (prepayId == null || prepayId.equals("")) {
        throw new RuntimeException("get prepayid error,");
    }
后台出错无法判断具体出错原因，建议更改为：

String prepayId = wxMpPrepayIdResult.getPrepay_id();
    if (prepayId == null || prepayId.equals("")) {
        throw new RuntimeException("get prepayid error,"+wxMpPrepayIdResult.getReturn_msg());
    }

**Comment by ukid** [comment]
应该是配置WxMpInMemoryConfigStorage有问题，你是否设置了partenerid key

**Comment by zhoujinliang** [comment]
我使用没问题了，我只是说返回错误的消息的格式。

**Comment by liuguo** [comment]
为什么在使用支付接口时，调用微信后台，获取getPrepay_id时，一直报签名无效呢。
我使用的是1.18服务号版本的，求大神指导。

**Comment by oohusl** [comment]
签名是微信返回的吗？应该是配置WxMpInMemoryConfigStorage有问题，你是否设置了partenerid key？

**Comment by liuguo** [comment]
已经解决，确实是没有设置partenerid key导致，多谢答复

**Comment by liuguo** [comment]
已经解决，确实是没有设置partenerid key导致，多谢答复
