### ISSUE TITLE
为什么获取不到加密的消息？

### ISSUE THREAD

**Issue by ycads** [chanjarster/weixin-java-tools#159]
感谢有这个组件，现在有个问题需要帮忙：
WxMpXmlOutMessage outMessage = wxMpMessageRouter.route(inMessage);
			System.out.println(" #### " + outMessage);
获取到的outMessage为null，是什么原因呢？

**Comment by chanjarster** [comment]
router默认是异步的，异步的返回的都是null，除非你规定某个rule是同步的才可以
