### ISSUE TITLE
WxConsts.EVT_CLICK 常量定义的的大写的CLICK，但是实际中微信发过来的消息里click是小写导致路由匹配不上

### ISSUE THREAD

**Issue by superhanliu** [chanjarster/weixin-java-tools#168]
WxConsts.EVT_CLICK 常量定义的的大写的CLICK，但是实际中微信发过来的消息里click是小写导致路由匹配不上

**Comment by superhanliu** [comment]
貌似有个BUTTON_CLICK是小写的。。。这2者如何区分？

**Comment by chanjarster** [comment]
http://mp.weixin.qq.com/wiki/2/5baf56ce4947d35003b86a9805634b1e.html

http://mp.weixin.qq.com/wiki/9/981d772286d10d153a3dc4286c1ee5b5.html

微信的文档里是大写CLICK

**Comment by superhanliu** [comment]
我是企业号测试的。

微信发来的消息:WxCpXmlMessage{agentId=4, toUserName='wxec3b430993851905', fromUserName='testliuhan', createTime=1436852992, msgType='event', content='null', msgId=null, picUrl='null', mediaId='null', format='null', thumbMediaId='null', locationX=null, locationY=null, scale=null, label='null', title='null', description='null', url='null', event='click', eventKey='reg', ticket='null', latitude=null, longitude=null, precision=null, recognition='null', status='null', totalCount=null, filterCount=null, sentCount=null, errorCount=null, scanCodeInfo=null, sendPicsInfo=null, sendLocationInfo=null}

看其中 event='click'

**Comment by chanjarster** [comment]
我去，企业号文档里也是大写CLICK

http://qydev.weixin.qq.com/wiki/index.php?title=接收事件#.E4.B8.8A.E6.8A.A5.E8.8F.9C.E5.8D.95.E4.BA.8B.E4.BB.B6
