### ISSUE TITLE
动态获取消息路由规则的问题

### ISSUE THREAD

**Issue by JounQin** [chanjarster/weixin-java-tools#169]
目前我们的项目要求消息路由规则是可以随时更改的，而路由在应用中实际上是单例的，暂时没有找到直接按需求重新配置消息路由规则的地方，只能先使用反射将wxMpMessageRouter实例中的rules重置再重新填入新的路由规则。

        try {
            Field field = WxMpMessageRouter.class.getDeclaredField("rules");
            field.setAccessible(true);
            field.set(msgRouter, new ArrayList<WxMpMessageRouterRule>());
        } catch (NoSuchFieldException e) {
            throw new RuntimeException(e);
        } catch (IllegalAccessException e) {
            throw new RuntimeException(e);
        }

        List<MsgRouterRule> rules = msgService.getMsgRouterRules();

        for (final MsgRouterRule rule : rules) {
            final MsgRouterRule innerRule = rule;

            logger.info("rule:{}", rule);

            msgRouter
                    .rule()
                    .async(false)
                    .msgType(rule.getInMsgType())
                    .content(rule.getInMsgContent())
                    .rContent(rule.getInMsgRContent())
                    .event(rule.getInEvent())
                    .eventKey(rule.getInEventKey())
                    .handler(new WxMpMessageHandler() {
                        @Override
                        public WxMpXmlOutMessage handle(WxMpXmlMessage wxMessage, Map<String, Object> context, WxMpService wxMpService, WxSessionManager sessionManager) throws WxErrorException {
                            logger.info("innerRule:{}", innerRule);

                            String outMsgType = innerRule.getOutMsgType();
                            switch (outMsgType) {
                                case (XML_MSG_TEXT): {
                                    return OutMessageUtil.initBuilder(WxMpXmlOutMessage.TEXT(), wxMessage).content(rule.getOutMsgContent()).build();
                                }
                                case (XML_MSG_NEWS): {
                                    List<Item> items = rule.getItems();
                                    NewsBuilder builder = OutMessageUtil.initBuilder(WxMpXmlOutMessage.NEWS(), wxMessage);
                                    for (Item item : items) {
                                        builder.addArticle(item);
                                    }
                                    return builder.build();
                                }
                                default: {
                                    return OutMessageUtil.initBuilder(WxMpXmlOutMessage.TEXT(), wxMessage).content(ResUtils.getKey("defaultOutMessage")).build();
                                }
                            }
                        }
                    })
                    .end();
        }

**Comment by JounQin** [comment]
但是这样操作以后回复时好时坏，如果操作过快，一更新路由内容就测试回复消息，Tomcat会报错，确认已将OutMessage封装完成，logger中正常输出，但是微信客户端经常收不到消息或中文被替换为'?'。如果操作后过段时间再进行回复消息测试是没有问题的，可能是服务器性能不行的问题？


        七月 15, 2015 5:12:13 下午 org.apache.catalina.connector.CoyoteAdapter checkRecycled
        信息: Encountered a non-recycled response and recycled it forcedly.
                org.apache.catalina.connector.CoyoteAdapter$RecycleRequiredException
        at org.apache.catalina.connector.CoyoteAdapter.checkRecycled(CoyoteAdapter.java:592)
        at org.apache.coyote.http11.AbstractHttp11Processor.recycle(AbstractHttp11Processor.java:1814)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.release(Http11Protocol.java:140)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:703)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

**Comment by chanjarster** [comment]
我觉得动态的rule的话就不能这么搞了，只能router用一个rule，而这个rule是所有消息都接受的。

然后这个rule里面自己动态更新处理规则。

**Comment by JounQin** [comment]
1个rule的话消息路由的实用性就大大降低了，又需要大量的if..else赘余语句，这应该和使用消息路由的初衷是相背离吧？

**Comment by chanjarster** [comment]
这个是设计的问题了，大量的if。。。else。。。显然是有问题的，那么你自己实现一种动态Rule。
