### ISSUE TITLE
JS_API文档错误

### ISSUE THREAD

**Issue by biezhi** [chanjarster/weixin-java-tools#171]
[https://github.com/chanjarster/weixin-java-tools/wiki/MP_js_api](https://github.com/chanjarster/weixin-java-tools/wiki/MP_js_api)
中

`public WxMpJsapiSignature createJsapiSignature(String url) throws WxErrorException;`

应为

`WxJsapiSignature wx =wxService.createJsapiSignature(String url);`

**Comment by chanjarster** [comment]
这个不算一个问题吧，我写的是方法签名，你写的是sample code
