### ISSUE TITLE
什么时候 出个非maven项目啊

### ISSUE THREAD

**Issue by shiguoxu** [chanjarster/weixin-java-tools#175]
求一个非maven项目源码，楼主。。本人不太会用maven，将maven项目导入Eclipse中也看不到各个实体类，或方法的具体实现

**Comment by chanjarster** [comment]
现在这年头不会用maven都不好意思和人打招呼。
还是学学吧。

**Comment by shiguoxu** [comment]
好的，谢谢。。我会好好学习的
