### ISSUE TITLE
获取永久素材的返回的对象如何取到图文页的URL信息？

### ISSUE THREAD

**Issue by LauRocky** [chanjarster/weixin-java-tools#188]
看了一下 代码，没有对获取到的永久图文页的URL进行赋值，不知道是处于什么考虑？如果需要使用到这个url的话，应该是怎么获取？

**Comment by chanjarster** [comment]
@codepiano  哥们儿帮忙解答一下？

**Comment by codepiano** [comment]
@LauRocky 上传图文类型的永久素材不会返回url，上传图片等其他类型的才会，请先看wiki: https://github.com/chanjarster/weixin-java-tools/wiki/MP_%E6%B0%B8%E4%B9%85%E7%B4%A0%E6%9D%90%E7%AE%A1%E7%90%86#%E6%B7%BB%E5%8A%A0%E5%9B%BE%E6%96%87%E6%B0%B8%E4%B9%85%E7%B4%A0%E6%9D%90
