### ISSUE TITLE
MP_自定义菜单管理

### ISSUE THREAD

**Issue by yongjiliu** [chanjarster/weixin-java-tools#199]
调用wxMenu.fromJson()定义菜单时，会出现异常。
![image](https://cloud.githubusercontent.com/assets/8488332/9373832/6bf5a9be-4721-11e5-9f31-8cba0a0f0a10.png)

**Comment by chanjarster** [comment]
看看源代码的注释能否有点启发？

https://github.com/chanjarster/weixin-java-tools/blob/f0432e6930ac2674427be2442b07ef01ae73ff82/weixin-java-common/src/main/java/me/chanjar/weixin/common/util/json/WxMenuGsonAdapter.java#L66

**Comment by yongjiliu** [comment]
解决了，谢谢。还想问一下，框架中是不是还没有加入语音识别功能？

2015-08-20 14:50 GMT+08:00 Daniel Qian <notifications@github.com>:

**Comment by yongjiliu** [comment]
不好意思，是我逗比了，语音识别根本不需要在封装

在 2015年8月20日 下午3:59，刘永吉 <yongjiliu6@gmail.com>写道：
