### ISSUE TITLE
WxMpServiceImpl中的oauth2buildAuthorizationUrl方法是否存在错误？

### ISSUE THREAD

**Issue by nonesuccess243** [chanjarster/weixin-java-tools#200]
接口说明写的返回值为code，我的理解是服务器端返回的用于获取token的code，但代码实现中，是拼接了一个获取code的url返回出来，是否实际实现和接口文档不符？

**Comment by markfredchen** [comment]
没有问题。可以正确使用。你是不是没有对redirect_url进行encoding?

**Comment by akwolf** [comment]
返回值为code是微信回调给你的，建议首先了解oauth2原理

**Comment by nonesuccess243** [comment]
不是说这个函数不能用，而是说文档和代码实现不符
文档中写的返回值是code
```java
/**
   * <pre>
   * 构造oauth2授权的url连接
   * 详情请见: http://mp.weixin.qq.com/wiki/index.php?title=网页授权获取用户基本信息
   * </pre>
   * @param scope
   * @param state
   * @return code
   */
  public String oauth2buildAuthorizationUrl(String scope, String state);

```

而函数的实际含义，应该返回的是url

**Comment by chanjarster** [comment]
返回的url是给你在网页里使用的，所以这里不会直接返回给你code

http://mp.weixin.qq.com/wiki/17/c0f37d5704f0b64713d5d2c37b468d75.html
