### ISSUE TITLE
1.2.0版本中用户性别设置的问题

### ISSUE THREAD

**Issue by shaoweijin** [chanjarster/weixin-java-tools#206]
1.2.0版本中WxCpUserGsonAdapter 类中序列化user对象时，设置性别属性跟现在的微信接口不一致
 if (user.getGender() != null) {
      o.addProperty("gender", user.getGender().equals("男") ? 0 : 1);
    }

微信接口文档显示为
gender	否	性别 1表示男性，2表示女性

麻烦作者看一下

**Comment by chanjarster** [comment]
感谢 和issue #189 有关，在下一次1.2.1发布时就解决了，届时不会返回中文
