### ISSUE TITLE
临时二维码获取的场景id范围问题

### ISSUE THREAD

**Issue by aroundsm** [chanjarster/weixin-java-tools#210]
官方文档中给出的场景id范围：
scene_id	场景值ID，临时二维码时为32位非0整型，永久二维码时最大值为100000（目前参数只支持1--100000）
我在项目中调用方法WxMpService.qrCodeCreateTmpTicket(int scene_id, Integer expire_seconds)时，产生的scene_id超过int型的最大值，在调用时出现Integer.parse(scene_id)失败
所以方法中的scene_id是不是应该可以设置为long或double类型更合理

**Comment by chanjarster** [comment]
没有太明白，32位非0整型不就是Integer吗？

**Comment by aroundsm** [comment]
是我理解错了，我以为是32位数字的整型...那微信设置这个范围岂不是也限制临时二维码的数量，搞不懂

**Comment by chanjarster** [comment]
临时二维码是有时效的，过期了可以循环使用。

**Comment by aroundsm** [comment]
嗯，非常感谢您提供如此强大的工具！
