### ISSUE TITLE
有个方法名的问题请教下

### ISSUE THREAD

**Issue by rplees** [chanjarster/weixin-java-tools#212]
WxMpOAuth2AccessToken wxMpOAuth2AccessToken = wxMpService.oauth2getAccessToken(code);

这个 oauth2getAccessToken 方法名的 数字[2]后面的 g 小写是有什么规范标准支持的还是？

**Comment by chanjarster** [comment]
只是觉得如果是 ``oauth2GetAccessToken`` 看着有点不顺眼，可能并没有遵循什么标准

**Comment by rplees** [comment]
嘿嘿。明白。
