### ISSUE TITLE
新版本发布时间？

### ISSUE THREAD

**Issue by zxkane** [chanjarster/weixin-java-tools#215]
可否发布新版本包含近期`develop`分支改动？如果已有计划，可否告知发布安排？

**Comment by chanjarster** [comment]
刚才已发布1.3.1，因中央仓库同步可能需要一些时间，所以你需要等一会儿

**Comment by zxkane** [comment]
谢谢!


Kane

2015-10-16 10:16 GMT+08:00 Daniel Qian <notifications@github.com>:

**Comment by jaychang9** [comment]
特地来感谢下作者
