### ISSUE TITLE
WxMpService在Spring @Autowired时无法自动载入bean

### ISSUE THREAD

**Issue by alagerald** [chanjarster/weixin-java-tools#227]
使用@Autowired:

public class WeixinServiceImpl implements WeixinService,InitializingBean {
 @Autowired(required=true)
 @Qualifier("wxMpServiceImpl")
  private WxMpService wxMpService;
...
}

Spring 报错，无法找到qualified bean.
============================
可能的解决办法：
在WxMpServiceImpl.java里，加入：
 
import org.springframework.stereotype.*;
@Component
public class WxMpServiceImpl implements WxMpService {

**Comment by liukaitj** [comment]
用XML或者@Bean配置Spring Bean不行吗？这样对本框架源代码没有侵入的

**Comment by chanjarster** [comment]
看这个：

http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#beans-java-basic-concepts

**Comment by alagerald** [comment]
修改程序如下：    
@Bean
  public WxMpService wxMpServiceImpl(){
         return new me.chanjar.weixin.mp.api.WxMpServiceImpl();
  }
  private WxMpService wxMpService;

public void init() {
   wxMpService = wxMpServiceImpl();
...
}

问题解决！
多谢！
