### ISSUE TITLE
请问为什么我无法进行安全模式的消息收发?

### ISSUE THREAD

**Issue by joway** [chanjarster/weixin-java-tools#244]
我完全是按照文档来的, 也没有报错, 明文模式都是可以的,但是就是安全模式不行,兼容模式也不行(微信报该公众号暂时无法提供服务). 这个是因为微信的加密算法改了还是我自己的问题?

**Comment by superhanliu** [comment]
貌似我的服务号也有这个问题，因为时间紧迫就改用明文了。而就又没机会继续测试了

**Comment by superhanliu** [comment]
今天重点研究了一下这个问题，原来启用安全模式和明文模式，在公众号里参数分别是 msg_signature 和 signature ，如果全部都采用signature参数则安全模式下会提示校验签名失败。

**Comment by superhanliu** [comment]
String encryptType = req.getParameter("encrypt_type");
		String signature = null;
		if(wxConfig.isMpPlatForm()){//公众号
			if("aes".equals(encryptType))
				signature = req.getParameter("msg_signature");//公众号加密时是msg_signature
			else
				signature = req.getParameter("signature");//公众号不加密时是signature
		}else{//企业号
			signature = req.getParameter("msg_signature");//企业号	肯定是加密的
		}

**Comment by joway** [comment]
@superhanliu  原来如此，感谢!

**Comment by binarywang** [comment]
msg_signature是用来对消息进行加解密的，只有在消息开启安全模式时才会存在；
而signature则是用来校验请求来源的，确保请求是从微信服务器发出的，无论在何种模式下都会存在。
