### ISSUE TITLE
httpclient没有close， CloseableHttpResponse也没有close

### ISSUE THREAD

**Issue by sugar-xj** [chanjarster/weixin-java-tools#256]
每天5AM 我的程序会启动10个线程同步所有用户的信息，但是每隔3天我就必须重启tomcat，原因是close—wait 的tcp链接很多，没有释放
CloseableHttpResponse response = httpclient.execute(httpGet)) 

httpclient 和 CloseableHttpResponse 没有调用 close方法

try (CloseableHttpResponse response = httpclient.execute(httpGet)) {
      String responseContent = Utf8ResponseHandler.INSTANCE.handleResponse(response);
      WxError error = WxError.fromJson(responseContent);
      if (error.getErrorCode() != 0) {
        throw new WxErrorException(error);
      }
      return responseContent;
    }finally {
            response.close();
            httpclient.close();
      }

**Comment by binarywang** [comment]
这确实是个硬伤，不过你的写法也有待改善，放到try后面的小括号里的closable变量是会自动关闭的，无需在finally块里显示关闭。

**Comment by simplecodecn** [comment]
显式关闭会不会更好呢？

**Comment by chanjarster** [comment]
https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

``
Note: A try-with-resources statement can have catch and finally blocks just like an ordinary try statement. In a try-with-resources statement, any catch or finally block is run after the resources declared have been closed.
``

**Comment by binarywang** [comment]
@simplecodecn 显示关闭也得在finally里能访问到该变量，但事实是，try后面括号里面的变量作用域只在其后面的大括号范围内有效，finally里根本访问不到，你自己写代码就知道怎么回事了，另外看看 @chanjarster 提供的文章也就明白了。
