### ISSUE TITLE
上传永久图片素材，有错误

### ISSUE THREAD

**Issue by tongxing** [chanjarster/weixin-java-tools#267]
我的代码
       String imgName = uuid + type;
        File fileImg = new File(dir + "/" + imgName);
            file.transferTo(fileImg);
            System.out.println("---------图片储存到本地成功，返回图片的文件-------");
            WxMpMaterial wxMaterial = new WxMpMaterial();
            wxMaterial.setFile(fileImg);
            wxMaterial.setName(uuid);
            WxMpMaterialUploadResult res = wxMpService.materialFileUpload("image", wxMaterial);
             System.out.println("微信端的ID "+res.getMediaId());

每次执行到上传，就会报连接错误。
java.lang.RuntimeException: java.net.SocketException: Connection reset
at me.chanjar.weixin.mp.api.WxMpServiceImpl.executeInternal(WxMpServiceImpl.java:758)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.execute(WxMpServiceImpl.java:705)
	at me.chanjar.weixin.mp.api.WxMpServiceImpl.materialFileUpload(WxMpServiceImpl.java:296)
java.net.SocketException: Connection reset

我使用的httpclient4.5的jar包，应该不是jar包的问题，请问各位有没有碰到过这类问题。请问是怎么解决的。

**Comment by binarywang** [comment]
我也最近发现有这个问题了，同样的代码，以前都好好的，现在却报这个错误了，看来有可能是腾讯做了限制禁止上传素材，或者偷偷做了什么修改，先研究下看看了
