### ISSUE TITLE
如何实现关注公众号自动推送一条消息

### ISSUE THREAD

**Issue by swmwlm** [chanjarster/weixin-java-tools#305]
如题，想在公众号被关注的时候，推送一条图文消息

**Comment by binarywang** [comment]
router里面加入subscribe事件，在对应的handler里面组装图文消息

**Comment by swmwlm** [comment]
thanks,明白了

**Comment by nullsz** [comment]
this.wxMpMessageRouter.
		rule().
		async(false).
		event("subscribe")
		.handler(subscribeEventHandler)
		.end();

**Comment by binarywang** [comment]
@swmwlm  问题解决后请及时关闭，谢谢~
