### ISSUE TITLE
如何实现那种点击自定义菜单中选项，附近XXX，获取用户的地理位置信息然后通过程序处理，最后以列表的方式推送消息返回给用户？

### ISSUE THREAD

**Issue by lqm627** [chanjarster/weixin-java-tools#306]
其实这样就涉及到了两个事件类型，一个是自定义菜单的CLICK，一个是LOCATION，使用那个消息路由器如何去编写才能满足？因为我见例子写的都是一个事件对应一个HANDLER,这样的话我写两个HANDLER，理论上就能实现对两个事件的处理；但是我想要的效果是点击这个附近XXX的选项，我要获取到用户的地理位置信息，传到程序中通过一些处理，然后返回一些地址信息，把这些地址信息列表的形式推送返回给用户；所以这个消息路由要的效果就是先满足CLICK事件，然后根据LOCATION事件得到用户的地理位置信息，通过程序处理后一列表形式返回给用户，我就不知道怎么去编写才能实现。

**Comment by binarywang** [comment]
地理位置信息你可以通过设置公众号里接口权限为每次都上报，然后每次上报的时候你处理该事件，把位置存到你的数据库里，然后等他点击菜单时把这个地理位置读出来，再进行操作。

**Comment by lqm627** [comment]
这样处理好像可以，但我之前测试这个LOCATION事件的时候，我是设置成那个每5秒上报一次的了，我在消息路由里面也对LOCATION事件进行捕捉，建立了一个HANDLER去处理，但是我感觉这个事件的捕捉好像不好控制，有时好像没能进到这个HANDLER里面。我见那个广东福彩的公众号中的附近投注站就是我想要的效果，他那样的效果也像你说的那样去做吗？@binarywang

**Comment by binarywang** [comment]
5秒上报一次的也是可以啊，在location事件对应的handler里读取位置信息是没问题的，你的代码写的可能有问题，要不不至于进不去的。我看了广东福彩的那个功能了，估计它也是这么做的。

顺便给你参考下我的部分代码：
`        // 上报地理位置事件
        this.router.rule().async(false).msgType(WxConsts.XML_MSG_EVENT)
            .event(WxConsts.EVT_LOCATION).handler(this.getLocationHandler())
            .end();
`

**Comment by binarywang** [comment]
@lqm627 如果你的问题解决了，就关掉吧，多谢~
