### ISSUE TITLE
如何把WxMpMaterialNewsArticle当成WxArticle进行被动消息回复？

### ISSUE THREAD

**Issue by mrhexin** [chanjarster/weixin-java-tools#309]
如何把WxMpMaterialNewsArticle当成WxArticle进行被动消息回复？

**Comment by moqijiasudu** [comment]
解决了吗？我也正研究这个问题

**Comment by mrhexin** [comment]
解决了。直接重新建一个WxArticle对象，由WxMpMaterialNewsArticle赋值即可。

**Comment by binarywang** [comment]
@mrhexin  解决后就把issue关闭了吧，多谢~
