### ISSUE TITLE
多个项目同时使用，如何确保accessToken的一致性

### ISSUE THREAD

**Issue by chushiyun2016** [chanjarster/weixin-java-tools#315]
现在我有两个项目A、B，同时引用了这个项目，A、B中都会用到accessToken，如何保证两边的token是一致的？ 目前我是将token放在redis中来实现的。谢谢！

**Comment by binarywang** [comment]
你的做法已经很不错了啊，你是想寻求更好的方法？

**Comment by chushiyun2016** [comment]
@binarywang  重写WxCpConfigStorage类，用来实现token放在redis缓存中
