### ISSUE TITLE
Github组织（wechat-group ） 欢迎有志于共同维护该微信SDK的同仁加入

### ISSUE THREAD

**Issue by binarywang** [chanjarster/weixin-java-tools#321]
Github组织：https://github.com/wechat-group ，欢迎有志于共同维护该微信SDK的同仁加入。
另有QQ群[343954419](http://shang.qq.com/wpa/qunwpa?idkey=078f7a153d243853e24cf2b542e7a6ccbf2a592bc138080f84d11297f736ec46) （点击号码上的链接即可弹出加入QQ群的窗口），也欢迎大家加入讨论相关问题。
有意加入的请回复，我将发出加入组织的邀请。

**Comment by nonesuccess243** [comment]
请问现在还可以报名吗

**Comment by binarywang** [comment]
@nonesuccess243 可以，已邀请
