### ISSUE TITLE
WxMpPayService refund 方法报错

### ISSUE THREAD

**Issue by lucyTheSlayer** [chanjarster/weixin-java-tools#332]
java.lang.ClassCastException: me.chanjar.weixin.mp.bean.pay.request.WxPayRefundRequest  cannot be cast to me.chanjar.weixin.mp.bean.pay.result.WxPayRefundResult
me.chanjar.weixin.mp.api.impl.WxMpPayServiceImpl.refund(WxMpPayServiceImpl.java:77)

貌似是WxPayRefundResult result = (WxPayRefundResult)xstream.fromXML(responseContent)此处强转出错了。
望大神解决！

**Comment by binarywang** [comment]
这个属于新版本里的东西，你提问问题应该去新的项目里面提交

**Comment by lucyTheSlayer** [comment]
好的
