### ISSUE TITLE
access_token expired 问题

### ISSUE THREAD

**Issue by xmushi** [chanjarster/weixin-java-tools#64]
![Uploading QQ截图20141231160923.jpg . . .]()
         me.chanjar.weixin.common.exception.WxErrorException: 微信错误 errcode=42001, errmsg=access_token expired
json:{"errcode":42001,"errmsg":"access_token expired"}

oauth2getUserInfo
WIKI上说会自动处理access_token过期的？怎么还会有这种错误？

**Comment by zhoujinliang** [comment]
楼上写的错误的，oauth2getuserinfo 用的就是公用的access token

**Comment by chanjarster** [comment]
@zhoujinliang 有问题请在原issue（ issue #104 ）反映，close掉的issue原则上是不能在添加comment的。
