### ISSUE TITLE
 rule拦截了菜单点击事件，返回文本内容，怎么总是出现空指针异常？

### ISSUE THREAD

**Issue by alwjava365** [chanjarster/weixin-java-tools#65]
response.getWriter().write(outMessage.toXml()); 这句微空指针，outMessage为null

**Comment by chanjarster** [comment]
你这个rule是同步的还是异步的？

如果rule是异步的，不管handler返回什么，router.route()只会返回null。

如果rule是同步的，router.route()才会返回你在handler里返回的东西。

rule默认都是异步的。

请多看wiki。

**Comment by Mavlarn** [comment]
针对这个，我有一个疑问，在收到微信事件以后，不管的文本、图片、扫描等等，都需要给微信回复一个消息，不然微信上就会出现“暂时无法提供服务”这样的错误。   
如果默认使用异步的方式处理这些事件，那么岂不是都会出现这个错误？

**Comment by binarywang** [comment]
@Mavlarn  你需要自己判断，如果route()方法返回是null，则给微信返回空字符串("")即可

**Comment by binarywang** [comment]
因为 route方法的返回值是个WxMpXmlOutMessage对象，而最终要给微信返回的是文本，要么是非空的xml，要么是空字符串，所以你需要自己去做处理了。

**Comment by binarywang** [comment]
> response.getWriter().write(outMessage.toXml());
也就是这里需要分支判断下：
```
if(outMessage==null){
  response.getWriter().write("");
}else{
  response.getWriter().write(outMessage.toXml());
}
```

**Comment by Mavlarn** [comment]
谢谢，我就是按上面的方式处理。   
只是以前我的理解有误，我以为异步处理的时候，handler会直接返回一个内容为空的outMessage。知道了，谢谢。
