### ISSUE TITLE
微信消息去重

### ISSUE THREAD

**Issue by nezhazheng** [chanjarster/weixin-java-tools#66]
有没有考虑实现去重功能？

**Comment by chanjarster** [comment]
你可以自己写个Interceptor，将所有的消息ID记录下来，发现有重复的直接return false。

尽量不要用同步消息回复，用异步消息回复。

**Comment by chanjarster** [comment]
试试1.0.7-SNAPSHOT

**Comment by nezhazheng** [comment]
Cool!

**Comment by chanjarster** [comment]
根据官方文档

## 公众号的排重方式

* 普通消息：关于重试的消息排重，推荐使用msgid排重。
  * http://mp.weixin.qq.com/wiki/10/79502792eef98d6e0c6e1739da387346.html
* 时间消息：关于重试的消息排重，推荐使用FromUserName + CreateTime 排重。
  * http://mp.weixin.qq.com/wiki/2/5baf56ce4947d35003b86a9805634b1e.html

## 企业号的排重方式

官方文档完全没有写，参照公众号的方式排重。

**Comment by gejun123456** [comment]
如果用户使用了回报地理信息的话那么该event 5秒便会发一次，create_time以及fromUserName均一样可能和其他event重复，建议加上event_key及agent_id.

**Comment by chanjarster** [comment]
create_time怎么可能一样？用户是无影手？还是微信平台有bug？

> 在 2015年1月22日，15:34，gejun123456 <notifications@github.com> 写道：
> 
> create_time

**Comment by gejun123456** [comment]
回报地理信息是自动发送的，你可以使用手机试下。

**Comment by gejun123456** [comment]
加上取消关注时微信会发多个msg，event为unsubscribe,除了agent_id其他内容都一样,希望去重时加上agent_id

**Comment by chanjarster** [comment]
好，这个在1.1.1里解决，我刚刚发了1.1.0，我会另开一个issue解决这个问题
