### ISSUE TITLE
能不能 gen(String charsetName,String... arr)   支持可传入 ，对不起我很我聊

### ISSUE THREAD

**Issue by lrn744809337** [chanjarster/weixin-java-tools#75]
private static String gen(String... arr) throws NoSuchAlgorithmException,
			UnsupportedEncodingException {
		Arrays.sort(arr);
		StringBuilder sb = new StringBuilder();
		for (String a : arr) {
			sb.append(a);
		}

		MessageDigest sha1 = MessageDigest.getInstance("SHA1");
		sha1.update(sb.toString().getBytes(charsetName));
		byte[] output = sha1.digest();
		return bytesToHex(output);
	}

**Comment by chanjarster** [comment]
不懂你在说什么。

关于如何提问请看这篇文章：[提问的艺术](http://blog.csdn.net/danky/article/details/1370632)
