### ISSUE TITLE
1.1.0企业帐号WxCpInMemoryConfigStorage没有expiresIn了啊

### ISSUE THREAD

**Issue by lqviwz** [chanjarster/weixin-java-tools#83]
改属性了啊 编译出错了。

**Comment by chanjarster** [comment]
属性改名了，改成expiresTime了。忘记在升级说明里说了，sorry

**Comment by chanjarster** [comment]
@lqviwz 我在[1.1.0升级指南](https://github.com/chanjarster/weixin-java-tools/wiki/1_1_0升级指南)详细说明了为啥会修改这个属性，请阅。

**Comment by lqviwz** [comment]
@chanjarster 谢谢，已改使用处代码。
