### ISSUE TITLE
WxMessageRouter、Rule提供setter方法，便于使用spring等依赖注入框架

### ISSUE THREAD

**Issue by lqviwz** [chanjarster/weixin-java-tools#87]
WxMessageRouter私有变量rules、Rule私有变量handlers可否添加读写访问器，便于在配置文件（如spring文件）进行配置

**Comment by chanjarster** [comment]
啥情况？挺有道理的啊。

**Comment by lqviwz** [comment]
发现Rule中涉及agentid、fromuser、content等等都需要公开写访问器才能在配置文件中配置。
于是我自己继承了 Rule和WxCpMessageRouter 然后就能在spring中配置了。 
比如rule  我扩展了个 setAgentId、setRegex ... setHandlers、setInterceptors， 在WxCpMessageRouter 扩展了setRules。
目前能满足需求了。

**Comment by chanjarster** [comment]
其实可以放开的。

**Comment by lqviwz** [comment]
嗯，有一些好处吧，刚学java，正摸索中。


    <bean id="ruleAll" class="com.amnet.weixin.api.Rule">
        <constructor-arg name="routerBuilder" ref="WxCpMessageRouter"/>
        <constructor-arg name="wxCpService" ref="wxService"/>
        <constructor-arg name="sessionManager" ref="sessionManager"/>
        <property name="handlers">
            <list>
                <ref bean="handler1"/>
            </list>
        </property>
        <property name="async" value="false"/>
        <property name="agentId" value="0"></property>
    </bean>

<bean id="handler0" class="com.amnet.weixin.messageHandler.LogHandler">
<property name="c" value="微信系统正在成长中，祝您工作愉快"></property>
</bean>
