### ISSUE TITLE
生成oauth2授权url连接方法里的回调url可自定义

### ISSUE THREAD

**Issue by sugar-xj** [chanjarster/weixin-java-tools#89]
授权url每次都返回一个url有些逻辑无法实现，而且的url是可以带参数，再增加个方法，谢谢

**Comment by chanjarster** [comment]
那个类？哪个方法？带什么参数？

**Comment by sugar-xj** [comment]
WxMpServiceImpl.oauth2buildAuthorizationUrl 方法。
下面是我的回调url：
redirect_uri=http%3A%2F%2Fwww.xxx.com%2Fmusic%2Fsearch.wx%3FfromMenu
我这个url是经常变化的，所带的参数也是。

**Comment by chanjarster** [comment]
我不知道为何redirect_uri会经常变，可能你的项目里同时维护了多个公众号。

但是这个项目设计的初衷是一个公众号或企业号用一套configStorage，service，router，如果你的项目要维护多个公众号或企业号，那么就需要自己维护多套这个东西。

简单来说这个项目旨在提供一个self-contain的工具，好处可以省掉一些参数，坏处是不够灵活。

如果你实在需要你所讲的这个需求，可以继承这个类，然后自己写一个方法。

**Comment by sugar-xj** [comment]
我的项目只用一个服务号，那个我自己写一个吧，
我的项目放在本地环境没问题，放在外网环境就出现这个
 java.lang.NoSuchFieldError: INSTANCE
WxMpServiceImpl类里，已经一天了，没找到解决方法
CloseableHttpClient httpClient 这个导致的，想要自己实现WxMpService 但是你的接口中的形参是这个CloseableHttpClient，导致自己实现还是要用这个类。。。。

**Comment by sugar-xj** [comment]
你能不能用commons-httpclient   替换所有http请求？自己实现WxMpService 还是要用CloseableHttpClient。

commons-httpclient 部分代码
GetMethod getMethod = new GetMethod(url);
		getMethod.getParams().setParameter(HttpMethodParams.RETRY_HANDLER,
				new DefaultHttpMethodRetryHandler(3, false));
		getMethod.getParams().setParameter("http.protocol.cookie-policy",CookiePolicy.BROWSER_COMPATIBILITY);
		HttpClient client = new HttpClient();
		try {
			int statusCode = client.executeMethod(getMethod);
			if (statusCode == HttpStatus.SC_OK) {

**Comment by chanjarster** [comment]
把你的``java.lang.NoSuchFieldError: INSTANCE``异常堆栈贴出来。

很有可能是你所说的“本地环境”的CLASSPATH和你所说的“外网环境”的CLASSPATH中所包含的jar不一样导致的冲突问题。

**Comment by chanjarster** [comment]
而且根据官方说明，commons-httpclient项目已经寿终正寝，所以我不会用commons-httpclient替代现在的httpcomponents

    The Commons HttpClient project is now end of life, and is no longer being developed. 
    It has been replaced by the Apache HttpComponents project in its HttpClient and HttpCore modules, 
    which offer better performance and more flexibility.
