### ISSUE TITLE
WxMpUser添加sexId字段，和微信返回的性别字段保持一致

### ISSUE THREAD

**Issue by sugar-xj** [chanjarster/weixin-java-tools#90]
WxUserGsonAdapter所转换的WxMpUser对象的性别按微信返回的值设置
不然所写的代码需要按照weixin-java-tools提供的的“男”，“女”，“未知”这三种来区分，而我们这边多了一个国际化的判断，或者在BD保存的转换

**Comment by chanjarster** [comment]
或者在BD保存的转换

什么意思？

**Comment by chanjarster** [comment]
关于这个设计当时的确欠考虑，不过为了向下兼容，我决定添加一个genderId的字段用来表示1，2，0
