### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by nezhazheng** [chanjarster/weixin-java-tools#93]
Hi
  代码洁癖可以有，但是对于一个被依赖的开源库来说，接口稳定性绝对是第一位的，应该尽量避免对暴露给用户使用的接口的改动，尤其是不兼容的这种，这个库用了好长时间了，非常棒，但是每次升级都很痛苦，希望在以后的升级中能注意这一点，不要随意改动接口了。

**Comment by chanjarster** [comment]
除了103 110 111三个版本之外，还有哪些wiki文档没说明的不兼容改动？

**Comment by zhoujinliang** [comment]
刷新access token

**Comment by chanjarster** [comment]
这个当时以为刷新access token这个功能是我的库里自己管理的，开发者应该不大会关心，也不大会用这个东西。所以就没写文档，我回头补一下。

**Comment by aimilin6688** [comment]
问下 这个sdk 有没有文档？

**Comment by chanjarster** [comment]
@aimilin6688 项目首页->README->“详细文档请看wiki”
