### ISSUE TITLE
同步处理和异步处理无法共存

### ISSUE THREAD

**Issue by sugar-xj** [chanjarster/weixin-java-tools#94]
异步
router.rule().async(false).msgType(WxConsts.XML_MSG_TEXT)....end();
同步
router.rule().async(true).msgType(WxConsts.XML_MSG_TEXT)....end();
这两个无法共存
除非顺序是先添加异步handler然后是同步handler
router.rule().async(true).msgType(WxConsts.XML_MSG_TEXT)....end();
router.rule().async(false).msgType(WxConsts.XML_MSG_TEXT)....end();
原因是：
for (final WxMpMessageRouterRule rule : rules) {
      if (rule.test(wxMessage)) {
        matchRules.add(rule);
        if(!rule.isReEnter()) {
          break;-------------------------》这部分直接跳出循环，没有判断后面有没有异步处理的handler
        }
      }
    }

**Comment by chanjarster** [comment]
不要用end()，用next()。

**Comment by sugar-xj** [comment]
从代码上看 next()  .isReEnter()是可以执行的，但是从逻辑上来说 异步 同步2个是不同的条件，这些条件足以让2个共存，为何还要增加一个 next（）？不是多此一举吗？

**Comment by chanjarster** [comment]
这个就好比

```java
if ( condition1 ) {
} else if ( condition2 ) {
}
```

和
```java
if ( condition1 ) {
}
if ( condition2 ) { 
}
```

的区别
