### ISSUE TITLE
问个问题，回复消息默认为什么是异步的？

### ISSUE THREAD

**Issue by alwjava365** [chanjarster/weixin-java-tools#97]
还有，.next是同步处理下一个路由么？是不是可以同时回复多条handler?

**Comment by chanjarster** [comment]
异步的话就能马上回复微信平台，这样就避免了微信平台因5秒内接受不到响应而重发消息的问题。

**Comment by chanjarster** [comment]
你对next的理解有点偏差，如果你匹配到一个消息，要有多个handler处理，那么你可以直接.handler(h1, h2, h3...)。

next的意思是一个消息在匹配了一个rule之后，还可以有机会匹配后面的rule。默认是一个消息匹配了一个rule之后就不会在继续匹配了。

**Comment by sugar-xj** [comment]
.handler(h1, h2, h3...)。是可以的，但是有些是同步，有些是异步的，
如果通过这个方法来增加h2异步handler  那么Async部分要自己实现，但你的代码中已经实现了async，我们再自己去异步化麻烦，你的逻辑要是能包含这个就好了

**Comment by chanjarster** [comment]
@sugar-xj 那就抄一下代码 :)
