### ISSUE TITLE
1.1.1 版本取消了刷新access token的方法？

### ISSUE THREAD

**Issue by zhoujinliang** [chanjarster/weixin-java-tools#98]
1.1.1 版本的wxcpservice中没看到有刷新access token的方法

当用企业号做跳转的时候会报access token过期的异常，但是这个接口（oauth2getUserInfo）应该是没去捕捉这个异常并重新获取access token，因此导致access token过期

**Comment by zhoujinliang** [comment]
找到了，集成到了getaccesstoken中去了。

**Comment by chanjarster** [comment]
我回头在wiki里写一下，漏了
