### ISSUE TITLE
Wx*MessageRouter.isDuplicateMessage方法逻辑错误

### ISSUE THREAD

**Issue by gejun123456** [chanjarster/weixin-java-tools#99]
String.valueOf(wxMessage.getEventKey() == null ? "" : wxMessage.getEvent());

影响不大，用户的event和create_time一般不会同时一样

**Comment by chanjarster** [comment]
的确是错了。。。

**Comment by gejun123456** [comment]
看了下数据，现在微信发的地理信息变成event为Location,建议去重加上event，谢谢罗

**Comment by chanjarster** [comment]
欧了
